server:
  port: 8080

rootPath: C:\Users\kayden\Desktop

temporaryRelativePath: \temp
temporaryPath: ${rootPath}${temporaryRelativePath}

uploadFilePath: ${rootPath}\uploadFile

previewRelativePath: \previewCover
previewCoverPath: ${rootPath}${previewRelativePath}

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bilicover?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: kayden
  servlet:
    multipart: 
      max-file-size: 10MB
      max-request-size: 100MB
  resources: 
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${rootPath} 